# Generated by Django 3.1 on 2020-08-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='language',
            field=models.CharField(choices=[('bangla', 'Bangla'), ('english', 'English'), ('BangEng', 'Bangla + English')], default='bangla', max_length=20),
        ),
    ]
