# Generated by Django 3.1 on 2020-08-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_app', '0002_imageupload_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='language',
            field=models.CharField(choices=[('ben', 'Bangla'), ('eng', 'English'), ('ben+eng', 'Bangla & English')], default='bangla', max_length=20),
        ),
    ]
